#!/bin/bash
#
# Creates Local.xcconfig with your Apple Developer Team ID.
# This file is gitignored and used for code signing.
#
# Usage:
#   ./Scripts/setup-local-config.sh TEAM_ID
#   ./Scripts/setup-local-config.sh -f TEAM_ID   # overwrite without prompting
#   ./Scripts/setup-local-config.sh              # prompts for team ID
#   DEVELOPMENT_TEAM=TEAM_ID ./Scripts/setup-local-config.sh
#

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
CONFIG_FILE="$PROJECT_ROOT/Local.xcconfig"

# Parse flags
FORCE=false
while [[ "$1" == -* ]]; do
    case "$1" in
        -f|--force) FORCE=true; shift ;;
        *) echo "Unknown option: $1" >&2; exit 1 ;;
    esac
done

# Get team ID from: argument > environment > stdin
if [[ -n "$1" ]]; then
    TEAM_ID="$1"
elif [[ -n "$DEVELOPMENT_TEAM" ]]; then
    TEAM_ID="$DEVELOPMENT_TEAM"
else
    echo "Enter your Apple Developer Team ID:"
    read -r TEAM_ID
fi

# Validate input
if [[ -z "$TEAM_ID" ]]; then
    echo "Error: No team ID provided" >&2
    exit 1
fi

# Validate format (10 alphanumeric characters)
if ! [[ "$TEAM_ID" =~ ^[A-Z0-9]{10}$ ]]; then
    echo "Warning: Team ID '$TEAM_ID' doesn't match expected format (10 alphanumeric characters)" >&2
    echo "Proceeding anyway..." >&2
fi

# Check for existing file with real content (not just the placeholder)
if [[ -f "$CONFIG_FILE" ]] && grep -q "DEVELOPMENT_TEAM" "$CONFIG_FILE"; then
    EXISTING_TEAM=$(grep "DEVELOPMENT_TEAM" "$CONFIG_FILE" | sed 's/.*= *//' | tr -d ' ;')
    if [[ "$EXISTING_TEAM" == "$TEAM_ID" ]]; then
        echo "Local.xcconfig already configured with DEVELOPMENT_TEAM = $TEAM_ID"
        exit 0
    fi
    echo "Existing Local.xcconfig found with DEVELOPMENT_TEAM = $EXISTING_TEAM"
    if [[ "$FORCE" != true ]]; then
        echo -n "Overwrite with $TEAM_ID? [y/N] "
        read -r CONFIRM
        if [[ ! "$CONFIRM" =~ ^[Yy]$ ]]; then
            echo "Aborted."
            exit 1
        fi
    fi
fi

# Write the config file
cat > "$CONFIG_FILE" << EOF
// Local.xcconfig
// This file is gitignored. Do not commit.
// Generated by Scripts/setup-local-config.sh

DEVELOPMENT_TEAM = $TEAM_ID
EOF

echo "Created $CONFIG_FILE with DEVELOPMENT_TEAM = $TEAM_ID"
